---

- name: Template duckdns dyndns IP service
  become: true
  template:
    src: duckdns.service.j2
    dest: /etc/systemd/system/duckdns.service
    owner: root
    group: root
    mode: '600'
  notify: reload systemd

- name: Copy duckdns timer for scheduled execution
  become: true
  copy:
    src: duckdns.timer
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '600'
  notify: reload systemd

- name: Enable system duckdns timer
  become: yes
  systemd:
    name: duckdns.timer
    state: started
    enabled: true
  notify: reload systemd
