---
# based on steps from here:
# https://pimylifeup.com/raspberry-pi-playstation-controllers/
# might want to add the joystick and checkinstall for deb package

- name: Install required dependencies for steamlink
  become: true
  ansible.builtin.package:
    name: "{{ steamlink_dependencies }}"

- name: Create sixpairing folder for ps3 controller support
  become: true
  ansible.builtin.file:
    path: "/root/{{ sixpairfolder }}"
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Download ps3pairing utils aka sixadd
  become: true
  ansible.builtin.git:
    repo: "{{ sixad }}"
    dest: "/root/{{ sixpairfolder }}/"
    version: "{{ sixad_tag_version }}"

- name: Compile sixadd
  become: true
  ansible.builtin.command: /usr/bin/make -C "/root/{{ sixpairfolder }}"
  changed_when: true

- name: Install sixadd
  become: true
  ansible.builtin.command: /usr/bin/make install -C "/root/{{ sixpairfolder }}"
  changed_when: true

- name: Start sixadd daemon on startup
  become: true
  ansible.builtin.systemd:
    name: sixad
    state: started
    enabled: true

- name: Increase gpu memory otherwise no video when streaming games
  become: true
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    line: "gpu_mem=256"
    create: true
    owner: root
    group: root
    mode: '644'
