---
# based on steps from here:
# https://pimylifeup.com/raspberry-pi-playstation-controllers/
# might want to add the joystick and checkinstall for deb package

- name: Install required dependencies for steamlink
  become: true
  package:
    name: "{{ steamlink_dependencies }}"

- name: create sixpairing folder for ps3 controller support
  become: true
  file:
    path: "/root/{{ sixpairfolder }}"
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Download ps3pairing utils aka sixadd 
  become: true
  ansible.builtin.git:
    repo: "{{ sixad }}"
    dest: "/root/{{ sixpairfolder }}/"
    depth: 1

- name: compile sixadd
  become: true
  command: /usr/bin/make -C "/root/{{ sixpairfolder }}"

- name: install sixadd
  become: true
  command: /usr/bin/make install -C "/root/{{ sixpairfolder }}"

- name: start sixadd daemon on startup
  become: true
  systemd:
    name: sixad
    state: started
    enabled: yes

- name: increase gpu memory otherwise no video when streaming games
  become: true
  lineinfile:
    path: /boot/config.txt
    line: "gpu_mem=256" 
    create: yes
