---

- name: Install packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Copy in VLAN NIC setup script
  template:
    src: vlan-nic-setup.j2
    dest: /usr/local/bin/vlan-setup.sh
    owner: root
    group: root
    mode: '0700'

- name: Copy in VLAN NIC systemd service unit file
  copy:
    src: vlan-setup.service
    dest: /etc/systemd/system/vlan-setup.service
    owner: root
    group: root
    mode: '0700'
  notify:
    - Reload systemd
  tags: vlan

- name: start VLAN NIC configure service
  systemd:
    name: vlan-setup
    state: started
    enabled: true

- name: Template dnsmasq config
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/homenet.conf
    owner: root
    group: root
    mode: '0600'
  notify:
    - Restart dnsmasq
  tags: dnsmasq

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Template nftables FW rules
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0700'
  tags: nftables
  notify:
    - Reload nftables

- name: Enable nftables service
  systemd:
    name: nftables
    state: started
    enabled: true
