---

- name: Detect arch for cloudflare deb
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: os_arch
  changed_when: false
  check_mode: false

- name: Download DNS over TLS Cloudflared
  ansible.builtin.get_url:
    url: "{{ cloudflared_release_ver }}{{ cloudflared_release_arch[os_arch.stdout] }}"
    dest: /tmp/cloudflared.deb
    owner: root
    group: root
    mode: '0700'

- name: Install DNS over TLS Cloudflared
  ansible.builtin.apt:
    deb: /tmp/cloudflared.deb
  when: not ansible_check_mode


- name: Copy DNS over TLS Cloudflare systemd service
  ansible.builtin.template:
    src: cloudflared.service.j2
    dest: /etc/systemd/system/cloudflared.service
    owner: root
    group: root
    mode: '0600'
  notify:
    - Reload systemd

- name: Add optional local or override DNS entries
  ansible.builtin.template:
    src: dns_hosts.conf.j2
    dest: /etc/dnsmasq.d/dns_hosts.conf
    owner: root
    group: root
    mode: '0600'
  notify:
    - Reload systemd
  tags: dns_hosts

- name: Enable DNS over TLS Cloudflare systemd service
  ansible.builtin.systemd:
    name: cloudflared
    state: started
    enabled: true
  when: not ansible_check_mode

- name: Clean up cloudflared download tmp files
  ansible.builtin.file:
    path: /tmp/cloudflared.deb
    state: absent
