---
- name: Disable WIFI and Bluetooth
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    insertafter: EOF
    path: /boot/config.txt
  loop:
    - dtoverlay=disable-wifi
    - dtoverlay=disable-bt
