---

- name:  Install packages
  become: true
  package: 
    name: "{{ packages }}"
    state: present

- name: Configure NFS export for root and boot
  template:
    src: templates/exports.j2
    dest: /etc/exports

- name: Enable tftpd and NFS 
  become: true
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:  "{{ packages }}"

