---

- name: Install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present

- name: Configure NFS export for root and boot
  template:
    src: templates/exports.j2
    dest: /etc/exports

- name: Configure tftpd boot directory
  lineinfile:
    path: /etc/default/tftpd-hpa
    regexp: '^TFTP_DIRECTORY='
    line: 'TFTP_DIRECTORY="{{ bootfs_path }}"'
    state: present

- name: Enable tftpd and NFS
  become: true
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ packages }}"
