---
- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
