---
- name: Reload nftables
  systemd:
    name: nftables
    state: reloaded

- name: Reload dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: true
