---

- name: Configure PI bootloader for tftpboot
  ansible.builtin.template:
    src: cmdline.txt.j2
    dest: /boot/cmdline.txt
    mode: '644'
    owner: root
    group: root

- name: Configure PI fstab to NFS mount filesytem post boot
  ansible.builtin.template:
    src: fstab.j2
    dest: /etc/fstab
    mode: '644'
    owner: root
    group: root
