---

- name: Configure PI bootloader for tftpboot
  template:
    src: cmdline.txt.j2
    dest: /boot/cmdline.txt

- name: Configure PI fstab to NFS mount filesytem post boot
  template:
    src: fstab.j2
    dest: /etc/fstab
    mode: '0644'
    owner: root
    group: root
