---
- name: Disable HDMI
  become: true
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    state: present
    regexp: "dtoverlay=vc4-kms-v3d"
    line: "dtoverlay=vc4-kms-v3d,nohdmi"

- name: Disable Activity LED
  become: true
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    state: present
    line: "{{ item }}"
  loop:
    - "dtparam=act_led_trigger=none"
    - "dtparam=act_led_activelow=on"
