---
name: Lint Yaml

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  Lint:
    name: lint
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install linters
        run: apt update && apt install ansible-lint -y --no-install-recommends

      - name: Setup ansible-lint and yamllint
        run: pip install ansible-lint yamllint

      - name: Run ansible-lint and yamllint
        run: yamllint .
