---

- name: Set hostname of machine to name specified in ansible inventory
  become: true
  ansible.builtin.command: hostnamectl set-hostname "{{ inventory_hostname }}"

- name: Set hostname in /etc/resolv.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1       localhost {{ inventory_hostname }}"
