---
name: Lint Yaml

on: [pull_request, workflow_dispatch]

jobs:
  yaml-lint:
    name: Yaml-lint
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install yamllint --yes --no-install-recommends

      - name: Run yamllint
        run: yamllint .
  ansible-lint:
    name: Ansible Lint 
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: "roles"
