---
name: Lint Yaml

on: [pull_request, workflow_dispatch]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install linters
        run: sudo apt-get update && sudo apt-get install ansible-lint --yes --no-install-recommends

      - name: Setup ansible-lint and yamllint
        run: pip install ansible-lint yamllint

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint roles/
