---

- name: Generate pihole admin password
  ansible.builtin.set_fact:
    kodi_admin_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=14') }}"

- name: Admin password set to below value (change to something else with pihole -a -p)
  ansible.builtin.debug:
    msg: "{{ kodi_admin_password }}"

- name: Install git
  become: true
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true
    install_recommends: false

- name: Make pi-hole directory
  become: true
  ansible.builtin.file:
    path: /etc/pihole/
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Template pi-hole config
  become: true
  ansible.builtin.template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: '0755'

- name: Fetch pihole
  become: true
  ansible.builtin.git:
    repo: https://github.com/pi-hole/pi-hole.git
    dest: /root/pi-hole/
    depth: 1
    version: "{{ pihole_release_version }}"
  when: not ansible_check_mode

- name: Install unattended pihole
  ansible.builtin.command: /root/pi-hole/automated\ install/basic-install.sh --unattended
  changed_when: true

- name: Upgrade pihole
  ansible.builtin.command: /usr/local/bin/pihole -up
  become: true
  register: pihole_upgrade_log_output
  changed_when: true
  tags: upgrade

- name: Show upgrade log output
  ansible.builtin.debug:
    msg: "{{ pihole_upgrade_log_output }}"
  tags: upgrade
